name: FSR4 der HTW Berlin
collections_dir: collections
collections:
  events:
    sort_by: date
  members:
    sort_by: last_name
    order:
      - 1_sebastian.md
      - 2_christian.md
      - 3_dustin.md
      - 4_michaela.md
  resorts:
  alumni:
    sort_by: last_name
