name: FSR4 der HTW Berlin
collections_dir: collections
collections:
  events:
    sort_by: date
  members:
    sort_by: last_name
    order:
      - lotte.md
      - dustin.md
      - luis.md
  resorts:
  alumni:
    sort_by: last_name
