name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build and deploy the website
    runs-on: linux-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Recommended: Use cache action to cache the installed gems for the project
      - name: Check cache for gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build
        uses: fsr4/jekyll-build@v2

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./_site
