name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test site using HTMLProof
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Recommended: Use cache action to cache the installed gems for the project
      - name: Check cache for gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build
        uses: fsr4/jekyll-build@v1

      - name: Test
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ./_site
          arguments: --assume-extension --check-html --disable-external --allow-hash-href