name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  deploy_production:
    name: Deploy to fsr4.students-htw.de
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./_site
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: ./_site
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

  deploy_backup:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./_site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site